FROM node:18-alpine

WORKDIR /app

# Copiar configuración de dependencias
COPY package*.json ./

RUN npm install

# Copiar el código fuente
COPY . .

EXPOSE 3000

# Lanzamos Vite con --host 0.0.0.0 para que escuche conexiones externas a la red del contenedor
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
